version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 10
exclude_patterns:
  - "apis/static/"
  - "apis/templates/"
  - "**/tests/"
