
language: python
python:
  - "3.6"
env:
  global:
    - CC_TEST_REPORTER_ID=184f9ed33bf792dbb14db87e8df368bd78c977a7837f39ee9ed8cc83ed28738d
  
install:
  - pip install -r requirements.txt
  
script:
  - pytest v1/tests.py
  

after_success:
  - coveralls

