
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_weconnectdb;" -U postgres
  - psql -c "CREATE USER tibzy;" -U postgres
env:
  - DATABASE_URL=postgresql://tibzy@localhost/test_weconnectdb SECRET_KEY=some_secret_value APP_SETTINGS=config.TestingConfig

script:
  - pytest apis/v2/.
  - coverage run --source='apis/v2/' manage.py test
  - coverage report
after_success:
  - coveralls
