
language: python
python: 
  - "3.6"
install: 
  - pip install -r requirements.txt
env: 
  - DATABASE_URL=postgresql://db_user:andela123@localhost/test_weconnectdb SECRET_KEY=some_secret_value FLASK_CONFIG=testing
before_script: 
  - psql -c 'create database test_weconnectdb;' -U postgres
  - psql -c "create user db_user with password 'andela123';" -U postgres
script: 
  - pytest apis/v2/tests/.
  - coverage run --source='apis/v2' manage.py test
  - coverage report"
after_success: 
  - coveralls
