
language: python
python:
  - "3.6"
env:
  global:
    - CC_TEST_REPORTER_ID=184f9ed33bf792dbb14db87e8df368bd78c977a7837f39ee9ed8cc83ed28738d
  
install:
  - pip install -r requirements.txt

# command to run tests    
script:
  - pytest apis/v2/tests/.
  - coverage run --source='.' --omit='run.py' manage.py test  
  - coverage report

# generate code climate report  
after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls

