"""empty message

Revision ID: 2f38aae31e30
Revises: 
Create Date: 2018-04-11 08:08:34.730330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f38aae31e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['created_by'], ['id'])
    op.add_column('reviews', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'author')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'created_by')
    # ### end Alembic commands ###
