"""empty message

Revision ID: 5be113c56905
Revises: 42c52a1cb504
Create Date: 2018-05-09 14:53:29.702956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be113c56905'
down_revision = '42c52a1cb504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('reviews_author_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['author_id'], ['id'])
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_author_fkey', 'reviews', 'users', ['author'], ['id'])
    op.drop_column('reviews', 'author_id')
    # ### end Alembic commands ###
