"""empty message

Revision ID: 8d6d2f6ef75f
Revises: 536bdf40dba2
Create Date: 2018-05-21 17:48:01.730975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6d2f6ef75f'
down_revision = '536bdf40dba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklists', sa.Column('expiration', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklists', 'expiration')
    # ### end Alembic commands ###
