"""empty message

Revision ID: b1401136f770
Revises: 8d6d2f6ef75f
Create Date: 2018-05-21 17:48:40.882041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1401136f770'
down_revision = '8d6d2f6ef75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklists', 'expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklists', sa.Column('expiration', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
